export type StatUnit = "flat" | "percent";

export type StatOption = {
  id: string;
  label: string;
  statKey: string;
  statLabel: string;
  min: number;
  max: number;
  unit: StatUnit;
  isReduction?: boolean;
};

export type EquipmentSlot = {
  id: string;
  label: string;
  subOptions: StatOption[];
  mainOptions: StatOption[];
  extraStatOptions?: StatOption[];
};

const withSlot = (slotId: string, options: StatOption[]) =>
  options.map((option) => ({ ...option, id: `${slotId}.${option.id}` }));

const weaponSubOptions = withSlot("weapon", [
  {
    id: "extra_atk",
    label: "Additional Attack",
    statKey: "additional_attack",
    statLabel: "Additional Attack",
    min: 1200,
    max: 2000,
    unit: "flat",
  },
  {
    id: "crit_rate",
    label: "Critical Rate",
    statKey: "critical_rate",
    statLabel: "Critical Rate",
    min: 420,
    max: 700,
    unit: "flat",
  },
  {
    id: "crit_dmg",
    label: "Critical Damage",
    statKey: "critical_damage",
    statLabel: "Critical Damage",
    min: 112,
    max: 187,
    unit: "flat",
  },
  {
    id: "sp_on_normal_hit",
    label: "SP Recovery on Normal Attack",
    statKey: "sp_recovery_on_normal_hit",
    statLabel: "SP Recovery on Normal Attack",
    min: 5,
    max: 12,
    unit: "flat",
  },
  {
    id: "skill_dmg_pct",
    label: "Skill Damage Increase",
    statKey: "skill_damage_percent",
    statLabel: "Skill Damage",
    min: 2,
    max: 4,
    unit: "percent",
  },
  {
    id: "dot_dmg_pct",
    label: "DOT Increase",
    statKey: "dot_damage_percent",
    statLabel: "DOT",
    min: 2,
    max: 4,
    unit: "percent",
  },
  {
    id: "plant_dmg_pct",
    label: "Plant Monster Damage",
    statKey: "plant_monster_damage_percent",
    statLabel: "Plant Monster Damage",
    min: 3,
    max: 7,
    unit: "percent",
  },
  {
    id: "beast_dmg_pct",
    label: "Wild Beast Monster Damage",
    statKey: "wild_beast_monster_damage_percent",
    statLabel: "Wild Beast Monster Damage",
    min: 3,
    max: 7,
    unit: "percent",
  },
  {
    id: "mutant_dmg_pct",
    label: "Mutant Monster Damage",
    statKey: "mutant_monster_damage_percent",
    statLabel: "Mutant Monster Damage",
    min: 3,
    max: 7,
    unit: "percent",
  },
  {
    id: "demon_dmg_pct",
    label: "Demon Monster Damage",
    statKey: "demon_monster_damage_percent",
    statLabel: "Demon Monster Damage",
    min: 3,
    max: 7,
    unit: "percent",
  },
  {
    id: "insect_dmg_pct",
    label: "Insect Monster Damage",
    statKey: "insect_monster_damage_percent",
    statLabel: "Insect Monster Damage",
    min: 3,
    max: 7,
    unit: "percent",
  },
]);

const glovesBootsSubOptions = withSlot("gloves_boots", [
  {
    id: "extra_def",
    label: "Additional Defense",
    statKey: "additional_defense",
    statLabel: "Additional Defense",
    min: 1012,
    max: 1687,
    unit: "flat",
  },
  {
    id: "crit_rate",
    label: "Critical Rate",
    statKey: "critical_rate",
    statLabel: "Critical Rate",
    min: 420,
    max: 700,
    unit: "flat",
  },
  {
    id: "crit_dmg",
    label: "Critical Damage",
    statKey: "critical_damage",
    statLabel: "Critical Damage",
    min: 112,
    max: 187,
    unit: "flat",
  },
  {
    id: "sp_natural_recovery",
    label: "Natural SP Recovery",
    statKey: "natural_sp_recovery",
    statLabel: "Natural SP Recovery",
    min: 5,
    max: 9,
    unit: "flat",
  },
  {
    id: "skill_dmg_pct",
    label: "Skill Damage Increase",
    statKey: "skill_damage_percent",
    statLabel: "Skill Damage",
    min: 2,
    max: 4,
    unit: "percent",
  },
  {
    id: "dot_dmg_pct",
    label: "DOT Increase",
    statKey: "dot_damage_percent",
    statLabel: "DOT",
    min: 2,
    max: 4,
    unit: "percent",
  },
  {
    id: "accuracy",
    label: "ACC",
    statKey: "acc",
    statLabel: "ACC",
    min: 225,
    max: 375,
    unit: "flat",
  },
  {
    id: "evasion",
    label: "Evasion",
    statKey: "evasion",
    statLabel: "Evasion",
    min: 225,
    max: 375,
    unit: "flat",
  },
  {
    id: "block",
    label: "Block",
    statKey: "block",
    statLabel: "Block",
    min: 225,
    max: 375,
    unit: "flat",
  },
  {
    id: "armor_pen",
    label: "PEN",
    statKey: "pen",
    statLabel: "PEN",
    min: 225,
    max: 375,
    unit: "flat",
  },
]);

const upperLowerSubOptions = withSlot("upper_lower", [
  {
    id: "crit_res",
    label: "Critical Resistance",
    statKey: "critical_resistance",
    statLabel: "Critical Resistance",
    min: 312,
    max: 520,
    unit: "flat",
  },
  {
    id: "extra_def",
    label: "Additional Defense",
    statKey: "additional_defense",
    statLabel: "Additional Defense",
    min: 1575,
    max: 2625,
    unit: "flat",
  },
  {
    id: "hp_natural_recovery",
    label: "Natural HP Recovery",
    statKey: "natural_hp_recovery",
    statLabel: "Natural HP Recovery",
    min: 123,
    max: 206,
    unit: "flat",
  },
  {
    id: "sp_out_of_combat",
    label: "SP Recovery Out of Combat",
    statKey: "sp_recovery_out_of_combat",
    statLabel: "SP Recovery Out of Combat",
    min: 12,
    max: 20,
    unit: "flat",
  },
  {
    id: "sp_natural_recovery",
    label: "Natural SP Recovery",
    statKey: "natural_sp_recovery",
    statLabel: "Natural SP Recovery",
    min: 5,
    max: 9,
    unit: "flat",
  },
  {
    id: "accuracy",
    label: "ACC",
    statKey: "acc",
    statLabel: "ACC",
    min: 150,
    max: 250,
    unit: "flat",
  },
  {
    id: "evasion",
    label: "Evasion",
    statKey: "evasion",
    statLabel: "Evasion",
    min: 150,
    max: 250,
    unit: "flat",
  },
  {
    id: "block",
    label: "Block",
    statKey: "block",
    statLabel: "Block",
    min: 150,
    max: 250,
    unit: "flat",
  },
  {
    id: "armor_pen",
    label: "PEN",
    statKey: "pen",
    statLabel: "PEN",
    min: 150,
    max: 250,
    unit: "flat",
  },
  {
    id: "skill_cd_reduct",
    label: "Skill Cooldown Reduction",
    statKey: "skill_cooldown_reduction_percent",
    statLabel: "Skill Cooldown Reduction",
    min: 4,
    max: 8,
    unit: "percent",
    isReduction: true,
  },
  {
    id: "kupole_cd_reduct",
    label: "Kupole Cooldown Reduction",
    statKey: "kupole_cooldown_reduction_percent",
    statLabel: "Kupole Cooldown Reduction",
    min: 4,
    max: 8,
    unit: "percent",
    isReduction: true,
  },
]);

const ringSubOptions = withSlot("ring", [
  {
    id: "extra_atk",
    label: "Additional Attack",
    statKey: "additional_attack",
    statLabel: "Additional Attack",
    min: 375,
    max: 625,
    unit: "flat",
  },
  {
    id: "crit_res",
    label: "Critical Resistance",
    statKey: "critical_resistance",
    statLabel: "Critical Resistance",
    min: 360,
    max: 600,
    unit: "flat",
  },
  {
    id: "crit_dmg",
    label: "Critical Damage",
    statKey: "critical_damage",
    statLabel: "Critical Damage",
    min: 75,
    max: 125,
    unit: "flat",
  },
  {
    id: "sp_out_of_combat",
    label: "SP Recovery Out of Combat",
    statKey: "sp_recovery_out_of_combat",
    statLabel: "SP Recovery Out of Combat",
    min: 12,
    max: 20,
    unit: "flat",
  },
  {
    id: "skill_dmg_pct",
    label: "Skill Damage Increase",
    statKey: "skill_damage_percent",
    statLabel: "Skill Damage",
    min: 3,
    max: 5,
    unit: "percent",
  },
  {
    id: "dot_dmg_pct",
    label: "DOT Increase",
    statKey: "dot_damage_percent",
    statLabel: "DOT",
    min: 3,
    max: 5,
    unit: "percent",
  },
  {
    id: "control_duration_reduct",
    label: "Control Effect Duration Reduction",
    statKey: "control_effect_duration_reduction_percent",
    statLabel: "Control Effect Duration Reduction",
    min: 3,
    max: 5,
    unit: "percent",
    isReduction: true,
  },
]);

const necklaceSubOptions = withSlot("necklace", [
  {
    id: "hp_natural_recovery",
    label: "Natural HP Recovery",
    statKey: "natural_hp_recovery",
    statLabel: "Natural HP Recovery",
    min: 123,
    max: 206,
    unit: "flat",
  },
  {
    id: "sp_on_normal_hit",
    label: "SP Recovery on Normal Attack",
    statKey: "sp_recovery_on_normal_hit",
    statLabel: "SP Recovery on Normal Attack",
    min: 5,
    max: 12,
    unit: "flat",
  },
  {
    id: "sp_out_of_combat",
    label: "SP Recovery Out of Combat",
    statKey: "sp_recovery_out_of_combat",
    statLabel: "SP Recovery Out of Combat",
    min: 12,
    max: 20,
    unit: "flat",
  },
  {
    id: "fire_target_dmg",
    label: "Damage vs Fire Target",
    statKey: "damage_vs_fire_target_percent",
    statLabel: "Damage vs Fire Target",
    min: 4,
    max: 7,
    unit: "percent",
  },
  {
    id: "ice_target_dmg",
    label: "Damage vs Ice Target",
    statKey: "damage_vs_ice_target_percent",
    statLabel: "Damage vs Ice Target",
    min: 4,
    max: 7,
    unit: "percent",
  },
  {
    id: "lightning_target_dmg",
    label: "Damage vs Lightning Target",
    statKey: "damage_vs_lightning_target_percent",
    statLabel: "Damage vs Lightning Target",
    min: 4,
    max: 7,
    unit: "percent",
  },
  {
    id: "earth_target_dmg",
    label: "Damage vs Earth Target",
    statKey: "damage_vs_earth_target_percent",
    statLabel: "Damage vs Earth Target",
    min: 4,
    max: 7,
    unit: "percent",
  },
  {
    id: "holy_target_dmg",
    label: "Damage vs Holy Target",
    statKey: "damage_vs_holy_target_percent",
    statLabel: "Damage vs Holy Target",
    min: 4,
    max: 7,
    unit: "percent",
  },
  {
    id: "dark_target_dmg",
    label: "Damage vs Dark Target",
    statKey: "damage_vs_dark_target_percent",
    statLabel: "Damage vs Dark Target",
    min: 4,
    max: 7,
    unit: "percent",
  },
  {
    id: "control_duration_reduct",
    label: "Control Effect Duration Reduction",
    statKey: "control_effect_duration_reduction_percent",
    statLabel: "Control Effect Duration Reduction",
    min: 3,
    max: 5,
    unit: "percent",
    isReduction: true,
  },
]);

const mainWeaponMainOptions = withSlot("main_weapon_main", [
  {
    id: "boss_dmg",
    label: "Boss Damage",
    statKey: "boss_damage_percent",
    statLabel: "Boss Damage",
    min: 6,
    max: 10,
    unit: "percent",
  },
  {
    id: "normal_monster_dmg",
    label: "Normal Monster Damage",
    statKey: "normal_monster_damage_percent",
    statLabel: "Normal Monster Damage",
    min: 24,
    max: 40,
    unit: "percent",
  },
]);

const subWeaponMainOptions = withSlot("sub_weapon_main", [
  {
    id: "boss_dmg",
    label: "Boss Damage",
    statKey: "boss_damage_percent",
    statLabel: "Boss Damage",
    min: 6,
    max: 10,
    unit: "percent",
  },
  {
    id: "normal_monster_dmg",
    label: "Normal Monster Damage",
    statKey: "normal_monster_damage_percent",
    statLabel: "Normal Monster Damage",
    min: 24,
    max: 40,
    unit: "percent",
  },
]);

const upperMainOptions = withSlot("upper_main", [
  {
    id: "clean_hit_pierce",
    label: "Clean Hit / Pierce Bonus",
    statKey: "clean_hit_pierce_bonus_percent",
    statLabel: "Clean Hit / Pierce Bonus",
    min: 8,
    max: 10,
    unit: "percent",
  },
  {
    id: "skill_dmg",
    label: "Skill Damage",
    statKey: "skill_damage_percent",
    statLabel: "Skill Damage",
    min: 2,
    max: 4,
    unit: "percent",
  },
  {
    id: "max_hp",
    label: "Max HP",
    statKey: "max_hp_percent",
    statLabel: "Max HP",
    min: 10,
    max: 14,
    unit: "percent",
  },
]);

const lowerMainOptions = withSlot("lower_main", [
  {
    id: "cooldown_reduct",
    label: "Cooldown Reduction",
    statKey: "skill_cooldown_reduction_percent",
    statLabel: "Skill Cooldown Reduction",
    min: 3,
    max: 5,
    unit: "percent",
    isReduction: true,
  },
  {
    id: "crit_dmg",
    label: "Critical Damage",
    statKey: "critical_damage_percent",
    statLabel: "Critical Damage",
    min: 5,
    max: 7,
    unit: "percent",
  },
  {
    id: "max_hp",
    label: "Max HP",
    statKey: "max_hp_percent",
    statLabel: "Max HP",
    min: 10,
    max: 14,
    unit: "percent",
  },
]);

const glovesMainOptions = withSlot("gloves_main", [
  {
    id: "clean_hit_pierce",
    label: "Clean Hit / Pierce Bonus",
    statKey: "clean_hit_pierce_bonus_percent",
    statLabel: "Clean Hit / Pierce Bonus",
    min: 8,
    max: 10,
    unit: "percent",
  },
  {
    id: "crit_dmg",
    label: "Critical Damage",
    statKey: "critical_damage_percent",
    statLabel: "Critical Damage",
    min: 5,
    max: 7,
    unit: "percent",
  },
  {
    id: "blocked_reduct",
    label: "Blocked Reduction",
    statKey: "blocked_reduction_percent",
    statLabel: "Blocked Reduction",
    min: 1,
    max: 3,
    unit: "percent",
    isReduction: true,
  },
]);

const bootsMainOptions = withSlot("boots_main", [
  {
    id: "cooldown_reduct",
    label: "Cooldown Reduction",
    statKey: "skill_cooldown_reduction_percent",
    statLabel: "Skill Cooldown Reduction",
    min: 3,
    max: 5,
    unit: "percent",
    isReduction: true,
  },
  {
    id: "skill_dmg",
    label: "Skill Damage",
    statKey: "skill_damage_percent",
    statLabel: "Skill Damage",
    min: 2,
    max: 4,
    unit: "percent",
  },
  {
    id: "blocked_reduct",
    label: "Blocked Reduction",
    statKey: "blocked_reduction_percent",
    statLabel: "Blocked Reduction",
    min: 1,
    max: 3,
    unit: "percent",
    isReduction: true,
  },
]);

const mainWeaponExtraOptions = withSlot("main_weapon_extra", [
  {
    id: "attack_passive",
    label: "Attack",
    statKey: "attack_passive",
    statLabel: "Attack",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const subWeaponExtraOptions = withSlot("sub_weapon_extra", [
  {
    id: "attack_passive",
    label: "Attack",
    statKey: "attack_passive",
    statLabel: "Attack",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const upperExtraOptions = withSlot("upper_extra", [
  {
    id: "def_passive",
    label: "DEF Passive",
    statKey: "def_passive",
    statLabel: "DEF Passive",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const lowerExtraOptions = withSlot("lower_extra", [
  {
    id: "def_passive",
    label: "DEF Passive",
    statKey: "def_passive",
    statLabel: "DEF Passive",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const glovesExtraOptions = withSlot("gloves_extra", [
  {
    id: "acc",
    label: "ACC",
    statKey: "acc",
    statLabel: "ACC",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "pen",
    label: "PEN",
    statKey: "pen",
    statLabel: "PEN",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "block",
    label: "Block",
    statKey: "block",
    statLabel: "Block",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "evasion",
    label: "Evasion",
    statKey: "evasion",
    statLabel: "Evasion",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const bootsExtraOptions = withSlot("boots_extra", [
  {
    id: "acc",
    label: "ACC",
    statKey: "acc",
    statLabel: "ACC",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "pen",
    label: "PEN",
    statKey: "pen",
    statLabel: "PEN",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "block",
    label: "Block",
    statKey: "block",
    statLabel: "Block",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "evasion",
    label: "Evasion",
    statKey: "evasion",
    statLabel: "Evasion",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const ringExtraOptions = withSlot("ring_extra", [
  {
    id: "attack_passive",
    label: "Attack",
    statKey: "attack_passive",
    statLabel: "Attack",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

const necklaceExtraOptions = withSlot("necklace_extra", [
  {
    id: "crit_dmg",
    label: "Crit Damage",
    statKey: "critical_damage",
    statLabel: "Critical Damage",
    min: 0,
    max: 999999,
    unit: "flat",
  },
  {
    id: "hp",
    label: "HP",
    statKey: "hp",
    statLabel: "HP",
    min: 0,
    max: 999999,
    unit: "flat",
  },
]);

export const EQUIPMENT_SLOTS: EquipmentSlot[] = [
  {
    id: "main_weapon",
    label: "Main Weapon",
    subOptions: weaponSubOptions,
    mainOptions: mainWeaponMainOptions,
    extraStatOptions: mainWeaponExtraOptions,
  },
  {
    id: "sub_weapon",
    label: "Sub Weapon",
    subOptions: weaponSubOptions,
    mainOptions: subWeaponMainOptions,
    extraStatOptions: subWeaponExtraOptions,
  },
  {
    id: "upper",
    label: "Upper",
    subOptions: upperLowerSubOptions,
    mainOptions: upperMainOptions,
    extraStatOptions: upperExtraOptions,
  },
  {
    id: "lower",
    label: "Lower",
    subOptions: upperLowerSubOptions,
    mainOptions: lowerMainOptions,
    extraStatOptions: lowerExtraOptions,
  },
  {
    id: "gloves",
    label: "Gloves",
    subOptions: glovesBootsSubOptions,
    mainOptions: glovesMainOptions,
    extraStatOptions: glovesExtraOptions,
  },
  {
    id: "boots",
    label: "Boots",
    subOptions: glovesBootsSubOptions,
    mainOptions: bootsMainOptions,
    extraStatOptions: bootsExtraOptions,
  },
  {
    id: "ring",
    label: "Ring",
    subOptions: ringSubOptions,
    mainOptions: [],
    extraStatOptions: ringExtraOptions,
  },
  {
    id: "necklace",
    label: "Necklace",
    subOptions: necklaceSubOptions,
    mainOptions: [],
    extraStatOptions: necklaceExtraOptions,
  },
];
